routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Auth::routes([
  'verify' => false,
  'reset' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/usuarios', 'HomeController@users');
Route::get('/usuarios/{id}/edit', 'HomeController@editUser');
Route::PATCH('/usuarios/{id}', 'HomeController@updateUser');
Route::DELETE('/usuarios/{id}', 'HomeController@destroy');
Route::post('/rusuarios/{id}', 'HomeController@RestorePass');
Route::post('/rsusuarios/{id}', 'HomeController@ResetPass');
Route::get('/listu', 'HomeController@table');
Route::resource('computadoras', 'ComputadoraController');
Route::resource('impresoras', 'ImpresoraController');
Route::resource('routers', 'RouterController');
Route::resource('switches', 'SwitchController');
Route::resource('departamentos', 'DepartamentosController');
Route::resource('mantenimientos', 'MantenimientoController');
Route::get('/modal', 'ComputadoraController@modal');
Route::get('/listc', 'ComputadoraController@table');
Route::get('/listd', 'DepartamentosController@table');
Route::get('/listi', 'ImpresoraController@table');
Route::get('/listr', 'RouterController@table');
Route::get('/lists', 'SwitchController@table');
Route::get('/listm', 'MantenimientoController@table');
Route::get('/listcd', 'ComputadoraController@show');
Route::get('/listid', 'ImpresoraController@show');

resources/views/acciones/create.blade.php
@extends('layouts.app')
@section('content')
<style>
	.card-header{
		background-color: #4390dc;
		color: #ffffff;
	}
</style>

<div class="container">
	<div class="card-header">
		Agregar Accion
	</div>
	<div class="card-body">
		@if($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
						<li> {{$error}} </li>
					@endforeach
				</ul>
			</div><br>
		@endif
		<form action="{{route('acciones.store')}}" method="post">
			@csrf
			

			<div class="form-group">
				<label for="nombre">Nombre</label>
			<input type="text" class="form-control" name="nombre" value="{{old('nombre')}}"></div>

			
			<button type="submit" class="btn btn-primary">Guardar</button>
			<a href="{{route('departamentos.index')}}" class="btn btn-danger">Cancelar</a>
		</form>
	</div>
</div>




@endsection

resources/views/acciones/edit.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Departamentos Editar</title>
@endsection
@section('content')
  <style>
   	.card-header{
   		background-color: #3490dc;
   		color: #ffffff;
   	}
  </style>

	<div class="container">
		<div class="card-header">
			Editar Accion
		</div>

		<div class="card-body">
			@if($errors->any())
		    <div class="alert alert-danger">
    			<ul>
    				@foreach($errors->all() as $error)
    					<li> {{$error}} </li>
    				@endforeach
    			</ul>
	      </div><br>
      @endif

  		<form action="{{route('acciones.update', $accion->id)}}" method="post">
  			@method('PATCH')
  			@csrf
  			<div class="form-group">
  			<label form="id">Id</label>
  			<input type="text" class="form-control" name="id" value="{{$accion->id}}">
  			</div>

  			<div class="form-group">
  			<label form="nombre">Nombre</label>
  			<input type="text" class="form-control" name="nombre" value="{{$accion->nombre}}">
  			</div>

  	

  			<button type="submit" class="btn btn-primary">Actualizar</button>
  		</form>
		</div>
	</div>
@endsection

resources/views/acciones/index.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Acciones</title>
@endsection
@section('content')
  <div class="container">
  	<h1>Acciones</h1>

  	<hr/>

  	@if(session()->get('mensaje'))
  	<div class="alert alert-succes">

  		{{session()->get('mensaje')}}
  	</div><br>

  	@endif
    <div class="table-responsive">
    	<table class="table table-stripped">
    		<thead>
          <tr>
            <td align="left" colspan="100%" style="padding:5px"><a href="{{route('acciones.create')}}" class="btn btn-primary">Nuevo</a></td>
          </tr>
    			<tr>
    				<td>ID</td>
    				<td>Nombre</td>
    				<td colspan="100%">Acciones</td>
    			</tr>

    		</thead>
    		<tbody>
    			@foreach($acciones as $accion)
    				<tr>
    					<td>{{$accion->id}}</td>
    					<td>{{$accion->nombre}}</td>
              <td><a href="{{route('acciones.show',$accion->id)}}" class="btn btn-primary">Ver</a></td>
    					<td><a href="{{route('acciones.edit', $accion->id)}}" class="btn btn-primary">Editar</a></td>
    					<td>
  						<form action="{{route('acciones.destroy', $accion->id)}}" method="post">
  							@csrf
  							@method('DELETE')
  							<button type="submit" class="btn btn-danger" onclick="return confirm('¿Estas seguro de eliminar?')" >Borrar</button>
  						</form>
    					</td>
    				</tr>
    			@endforeach
    		</tbody>
  		</table>
    </div>
  </div>
@endsection

resources/views/acciones/show.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Computadoras</title>
@endsection
@section('content')
  <div class="container">
  	<h1>Computadoras</h1>

  	<hr/>

  	@if(session()->get('mensaje'))
  	<div class="alert alert-succes">

  		{{session()->get('mensaje')}}
  	</div><br>

  	@endif
    <div class="table-responsive">
    	<table class="table table-stripped">
    		<thead>
          <tr>
            <td align="left" colspan="100%" style="padding:5px"><a href="{{route('computadoras.create')}}" class="btn btn-primary">Nuevo</a></td>
          </tr>
    			<tr>
    				<td>ID</td>
    				<td>Departamento</td>  
            <td>Sistema Operativo</td>
    				<td>Ram</td>
    				<td>Disco</td>
    				<td>Procesador</td>
    				<td>Modelo</td>
    				
    				<td>Caracteristicas</td>
    				
    			</tr>

    		</thead>
    		<tbody>
    			@foreach($computadoras as $computadora)
    				<tr>
    					<td>{{$computadora->id}}</td>
    					 <td>{{$deps[$computadora->Departamento]}}</td>
              <td>{{$computadora->SO}}</td>
    					<td>{{$computadora->Ram}}</td>
    					<td>{{$computadora->Disco}}</td>
    					<td>{{$computadora->Procesador}}</td>
    					<td>{{$computadora->Modelo}}</td>
    					
    					<td>{{$computadora->Caracteristicas}}</td>
    					<td align="center"><a href="{{route('computadoras.edit', $computadora->id)}}" class="btn btn-primary" title="Editar"><i class="fa fa-edit" aria-hidden="true"></i></a></td>
    					<td align="center">
  						<form action="{{route('computadoras.destroy', $computadora->id)}}" method="post">
  							@csrf
  							@method('DELETE')
  							<button type="submit" class="btn btn-danger" onclick="return confirm('¿Estas seguro de eliminar?')" title="Borrar"><i class="fa fa-trash" aria-hidden="true"></i></button>
  						</form>
    					</td>
    				</tr>
    			@endforeach
    		</tbody>
  		</table>
    </div>
  </div>
@endsection