routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Auth::routes([
  'verify' => false,
  'reset' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/usuarios', 'HomeController@users');
Route::get('/usuarios/{id}/edit', 'HomeController@editUser');
Route::PATCH('/usuarios/{id}', 'HomeController@updateUser');
Route::DELETE('/usuarios/{id}', 'HomeController@destroy');
Route::post('/rusuarios/{id}', 'HomeController@RestorePass');
Route::post('/rsusuarios/{id}', 'HomeController@ResetPass');
Route::get('/listu', 'HomeController@table');
Route::resource('computadoras', 'ComputadoraController');
Route::resource('impresoras', 'ImpresoraController');
Route::resource('routers', 'RouterController');
Route::resource('switches', 'SwitchController');
Route::resource('departamentos', 'DepartamentosController');
Route::resource('mantenimientos', 'MantenimientoController');
Route::get('/modal', 'ComputadoraController@modal');
Route::get('/listc', 'ComputadoraController@table');
Route::get('/listd', 'DepartamentosController@table');
Route::get('/listi', 'ImpresoraController@table');
Route::get('/listr', 'RouterController@table');
Route::get('/lists', 'SwitchController@table');
Route::get('/listm', 'MantenimientoController@table');
Route::get('/listcd', 'ComputadoraController@show');
Route::get('/listid', 'ImpresoraController@show');

app/Mantenimiento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mantenimiento extends Model
{
	//
	protected $table = 'mantenimiento';
    protected $fillable=[
    	'id',
    	'id_Equipo',
    	'tipo_equipo',
    	'usuario',
    	'acciones',
    	'observaciones'
	];
	
	public function departamento() {
        return $this->hasOne('App\Departamento', 'id', 'Departamento');
	}
	
	public function usuario(){
		return $this->hasOne('App\User', 'id', 'usuario');

	}
	
}

app/Http/Controllers/MantenimientoController.php
<?php

namespace App\Http\Controllers;

use App\Mantenimiento;
use Illuminate\Http\Request;

class MantenimientoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('mantenimientos.index');
    }

    public function table()
    {
        $mantenimientos = Mantenimiento::all();
        return $mantenimientos;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $mantenimientos = Mantenimiento::all();
        return view('mantenimientos.create', compact('mantenimientos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id_Equipo' => 'required',
            'tipo_equipo'=> 'required | integer',
            'usuario'=> 'required',
            'acciones'=> 'required | integer',
            'observaciones'=> 'required'

        ]);

        $mantenimiento = new Mantenimiento([
            'id_Equipo'=>$request->get('id_Equipo'),
            'tipo_equipo'=> $request->get('tipo_equipo'),
            'usuario'=> $request->get('usuario'),
            'acciones'=> $request->get('acciones'),
            'observaciones'=> $request->get('observaciones')


        ]);
        $mantenimiento->save();
        return redirect('mantenimientos')->with('mensaje', 'Agregado con exito' );

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Mantenimiento  $mantenimiento
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return Mantenimiento::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Mantenimiento  $mantenimiento
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $mantenimiento = Mantenimiento::findOrFail($id);
        return view('mantenimientos.edit', compact('mantenimiento'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Mantenimiento  $mantenimiento
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Mantenimiento $mantenimiento)
    {
        $request->validate([
            'id_Equipo' => 'required',
            'tipo_equipo'=> 'required | integer',
            'usuario'=> 'required',
            'acciones'=> 'required | integer',
            'observaciones'=> 'required'

        ]);

        $mantenimiento = Mantenimiento::find($id);
        $mantenimiento->id_Equipo= $request->get('id_Equipo');
        $mantenimiento->tipo_equipo = $request->get('tipo_equipo');
        $mantenimiento->usuario= $request->get('usuario');
        $mantenimiento->acciones= $request->get('observaciones');


       $mantenimiento->save();

        return redirect('mantenimientos')->with('mensaje', 'Actualizado con exito' );

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Mantenimiento  $mantenimiento
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $mantenimiento = Mantenimiento::find($id);
        $mantenimiento->delete();

        return "Eliminado correctamente";
    }
}

resources/views/mantenimientos/create.blade.php
@extends('layouts.app')

@section('content')
<style>
	.card-header{
		background-color: #4390dc;
		color: #ffffff;
	}
</style>

<div class="container">
	<div class="card-header">
		Registrar Mantenimiento
	</div>
	<div class="card-body">
		@if($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
						<li> {{$error}} </li>
					@endforeach
				</ul>
			</div><br>
		@endif

		<form action="{{route('mantenimientos.store')}}" method="post">
			@csrf


			<div class="form-group">
				<label for="equipo">Equipo</label>
				<button type="button" id="equipobtn" class="btn btn-secondary btn-block" data-toggle="modal" data-target="#InventarioModal">Seleccionar Equipo</button>
			</div>

			<div class="form-group">
				<label for="Nombre">Nombre</label>
			<input type="text" class="form-control" name="Nombre" value="{{old('Nombre')}}"></div>

			<div class="form-group">
				<p>Which programming languages do you like?</p>
         <form>
            <label class = "checkbox-inline">
               <input type = "checkbox" value = "">Java
            </label>
            <label class = "checkbox-inline">
               <input type="checkbox" value="">C++
            </label>
            <label class = "checkbox-inline">
               <input type = "checkbox" value = "">C
            </label>
         </form>
			</div>

			<button type="submit" class="btn btn-primary">Agregar</button>
			<a href="{{ url()->previous() }}" class="btn btn-danger">Cancelar</a>
		</form>
	</div><br><hr/>

	<h4>Orden de Mantenimiento</h4>

	<div class="table-responsive">
		<table class="table table-stripped">
			<thead>
				<tr>
					<td align="left" colspan="100%" style="padding:5px"><a href="{{route('mantenimientos.create')}}" class="btn btn-primary">Nuevo</a></td>
				</tr>
				<tr>
					<td>ID</td>
					<td>ID Equipo</td>
					<td>Equipo</td>
					<td>Encargado</td>
					<td>Mantenimiento</td>
					<td>Observaciones</td>
					<td colspan="100%">Acciones</td>
				</tr>

			</thead>
			<tbody>
				@foreach($mantenimientos as $mantenimiento)
					<tr>
						<td>{{$mantenimiento->id}}</td>
						<td> <a href="#"> {{$mantenimiento->id_Equipo}}</a></td>
						<td>{{$mantenimiento->tipo_equipo}}</td>
						<td>{{$mantenimiento->usuario}}</td>
						<td>{{$mantenimiento->acciones}}</td>
						<td>{{$mantenimiento->observaciones}}</td>
						<td align="center"><a href="{{route('mantenimientos.edit', $mantenimiento->id)}}" class="btn btn-primary" title="Editar"><i class="fa fa-edit" aria-hidden="true"></i></a></td>
						<td align="center">
						<form action="{{route('mantenimientos.destroy', $mantenimiento->id)}}" method="post">
							@csrf
							@method('DELETE')
							<button type="submit" class="btn btn-danger" onclick="return confirm('¿Estas seguro de eliminar?')" title="Borrar"><i class="fa fa-trash" aria-hidden="true"></i></button>
						</form>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>

	</div>
</div>
@endsection

resources/views/mantenimientos/edit.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Computadoras Editar</title>
@endsection
@section('content')
  <style>
   	.card-header{
   		background-color: #3490dc;
   		color: #ffffff;
   	}
  </style>

	<div class="container">
		<div class="card-header">
			Editar Computadora
		</div>

		<div class="card-body">
			@if($errors->any())
		    <div class="alert alert-danger">
    			<ul>
    				@foreach($errors->all() as $error)
    					<li> {{$error}} </li>
    				@endforeach
    			</ul>
	      </div><br>
      @endif

  		<form action="{{route('computadoras.update', $computadora->id)}}" method="post">
  			@method('PATCH')
  			@csrf
  			<div class="form-group">
  			<label form="SO">Sistema Operativo</label>
  			<input type="text" class="form-control" name="SO" value="{{$computadora->SO}}">
  			</div>

  			<div class="form-group">
  			<label form="Ram">Memoria Ram</label>
  			<input type="text" class="form-control" name="Ram" value="{{$computadora->Ram}}">
  			</div>

  			<div class="form-group">
  			<label form="Disco">Disco Duro</label>
  			<input type="text" class="form-control" name="Disco" value="{{$computadora->Disco}}">
  			</div>

  			<div class="form-group">
  			<label form="Procesador">Procesador</label>
  			<input type="text" class="form-control" name="Procesador" value="{{$computadora->Procesador}}">
  			</div>

  			<div class="form-group">
  			<label form="Modelo">Modelo</label>
  			<input type="text" class="form-control" name="Modelo" value="{{$computadora->Modelo}}">
  			</div>

  			<div class="form-group">
  			<label form="Departamento">Departamento</label>
  			<select  id="Departamento" name="Departamento" class="form-control">

                         <option value="{{$computadora->Departamento}}">{{$departamento->nombre}}</option>


                         @foreach($departamentos as $departamento)
                          <option value="{{$departamento->id}}">  {{$departamento->nombre}}  </option>
                         @endforeach
                         </select>
  			</div>

  			<div class="form-group">
  			<label form="Caracteristicas">Caracteristicas</label>
  			<input type="text" class="form-control" name="Caracteristicas" value="{{$computadora->Caracteristicas}}">
  			</div>

  			<button type="submit" class="btn btn-primary">Actualizar</button>
  			<a href="{{ url()->previous() }}" class="btn btn-danger">Cancelar</a>
  		</form>
		</div>
	</div>
@endsection

resources/views/mantenimientos/index.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Mantenimiento</title>
@endsection
@section('content')
  <div class="container">
  	<h1>Mantenimiento</h1>

  	<hr/>

  	@if(session()->get('mensaje'))
  	<div class="alert alert-succes">

  		{{session()->get('mensaje')}}
  	</div><br>

  	@endif
    <div id="toolbar">
      <p id="ActiveRoute" hidden>/mantenimientos/</p>
      <a href="{{route('mantenimientos.create')}}" title="Nuevo" class="btn btn-primary"><i class="fa fa-plus-circle"></i> </a>
      <button id="BtnEditar" title="Editar" class="btn btn-success"><i class="fa fa-edit"></i></button>
      <button id="BtnEliminar" title="Eliminar" class="btn btn-danger"><i class="fa fa-trash"></i></button>
    </div>
    <table
      id="tableInv"
      data-locale="es-MX"
      data-show-footer="true"
      data-show-export="true"
      data-export-types='["json", "xml", "csv", "txt", "pdf"]'
      data-export-options='{"fileName": "Mantenimientos", "jspdf": {"orientation":"landscape", "margins":{"left":30,"right":30,"bottom":30,"top":30}}}'
      data-show-refresh="true"
      data-toggle="table"
      data-sort-class="table-active"
      data-sortable="true"
      data-search="true"
      data-toolbar="#toolbar"
      data-single-select="true"
      data-click-to-select="true"
      data-page-list="[10, 25, 50, 100, All]"
      data-url="/listm"
      data-pagination="true">
      <thead>
        <tr>
          <th data-field="state" data-checkbox="true"></th>
          <th data-field="id" data-sortable="true">ID</th>
          <th data-field="id_Equipo" data-sortable="true">ID Equipo</th>
          <th data-field="tipo_equipo" data-sortable="true">Equipo</th>
          <th data-field="usuario" data-sortable="true">Encargado</th>
          <th data-field="acciones" data-sortable="true">Mantenimiento</th>
          <th data-field="observaciones" data-sortable="true">Observaciones</th>
        </tr>
      </thead>

    </table>
  </div>
@endsection