routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Auth::routes([
  'verify' => false,
  'reset' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/usuarios', 'HomeController@users');
Route::get('/usuarios/{id}/edit', 'HomeController@editUser');
Route::PATCH('/usuarios/{id}', 'HomeController@updateUser');
Route::DELETE('/usuarios/{id}', 'HomeController@destroy');
Route::post('/rusuarios/{id}', 'HomeController@RestorePass');
Route::post('/rsusuarios/{id}', 'HomeController@ResetPass');
Route::get('/listu', 'HomeController@table');
Route::resource('computadoras', 'ComputadoraController');
Route::resource('impresoras', 'ImpresoraController');
Route::resource('routers', 'RouterController');
Route::resource('switches', 'SwitchController');
Route::resource('departamentos', 'DepartamentosController');
Route::resource('mantenimientos', 'MantenimientoController');
Route::get('/modal', 'ComputadoraController@modal');
Route::get('/listc', 'ComputadoraController@table');
Route::get('/listd', 'DepartamentosController@table');
Route::get('/listi', 'ImpresoraController@table');
Route::get('/listr', 'RouterController@table');
Route::get('/lists', 'SwitchController@table');
Route::get('/listm', 'MantenimientoController@table');
Route::get('/listcd', 'ComputadoraController@show');
Route::get('/listid', 'ImpresoraController@show');

app/Departamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Departamento extends Model
{
    //

    protected $fillable =[
    	'id',
    	'nombre'
    ];

    public function depComp() {
        return $this->hasMany('App\Computadora', 'id', 'Departamento');
    }

    public function deptImp() {
        return $this->hasMany('App\Impresora', 'id', 'Departamento');
    }

    public function deptRou() {
        return $this->hasMany('App\Router', 'id', 'Departamento');
    }

    public function deptSwi() {
        return $this->hasMany('App\SwitchM', 'id', 'Departamento');
    }

}

app/Http/Controllers/DepartamentosController.php
<?php

namespace App\Http\Controllers;

use App\Departamento;
use App\Computadora;
use App\SwitchM;
use App\Router;
use App\Impresora;
use DB;
use Illuminate\Http\Request;

class DepartamentosController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    //metodo de listar datos
    return view('departamentos.index');

  }

  public function table()
  {
      $departamentos = Departamento::all();
      return $departamentos;
  }


   /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('departamentos.create');

        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([

            'nombre'=> 'required'
        ]);


        $departamento = new Departamento([

                       'nombre'=> $request->get('nombre')
        ]);
        $departamento->save();
        return redirect('departamentos')->with('mensaje', 'Agregado con exito' );


            }

    /**
     * Display the specified resource.
     *
     * @param  \App\Computadora  $computadora
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $computadoras = Computadora::where('Departamento', '=', $id)->get();
      $impresoras = Impresora::where('Departamento', '=', $id)->get();
      $departamento = Departamento::findOrFail($id);


      return view('departamentos.show', compact('computadoras', 'impresoras', 'departamento'));

        /*$departamentos = Departamento::all();



        foreach ($departamentos as $departamento) {

            $deps[$departamento['id']]=$departamento['nombre'];
        }

      $sql = "SELECT * FROM computadoras WHERE Departamento=? ";
        $computadoras= DB::select($sql,array($id));
         return view('departamentos.show', compact('computadoras', 'departamentos','deps'));*/
     }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Computadora  $computadora
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //editar computadpra
        $departamento = Departamento::findOrFail($id);
        return view('departamentos.edit', compact('departamento'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Computadora  $computadora
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
      $request->validate([

            'nombre'=> 'required'
        ]);


        $departamento = Departamento::find($id);
        $departamento->id = $request->get('id');
        $departamento->nombre= $request->get('nombre');

       $departamento->save();

        return redirect('departamentos')->with('mensaje', 'Actualizado con exito' );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Computadora  $computadora
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $departamento = Departamento::find($id);
        $departamento->delete();

        return redirect('departamentos')->with('mensaje','Registro Eliminado');

    }
}

resources/views/departamentos/create.blade.php
@extends('layouts.app')
@section('content')
<style>
	.card-header{
		background-color: #4390dc;
		color: #ffffff;
	}
</style>

<div class="container">
	<div class="card-header">
		Agregar Departamento
	</div>
	<div class="card-body">
		@if($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
						<li> {{$error}} </li>
					@endforeach
				</ul>
			</div><br>
		@endif
		<form action="{{route('departamentos.store')}}" method="post">
			@csrf


			<div class="form-group">
				<label for="nombre">Nombre</label>
			<input type="text" class="form-control" name="nombre" value="{{old('nombre')}}"></div>


			<button type="submit" class="btn btn-primary">Guardar</button>
			<a href="{{ url()->previous() }}" class="btn btn-danger">Cancelar</a>
		</form>
	</div>
</div>




@endsection

resources/views/departamentos/edit.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Departamentos Editar</title>
@endsection
@section('content')
  <style>
   	.card-header{
   		background-color: #3490dc;
   		color: #ffffff;
   	}
  </style>

	<div class="container">
		<div class="card-header">
			Editar Departamento
		</div>

		<div class="card-body">
			@if($errors->any())
		    <div class="alert alert-danger">
    			<ul>
    				@foreach($errors->all() as $error)
    					<li> {{$error}} </li>
    				@endforeach
    			</ul>
	      </div><br>
      @endif

  		<form action="{{route('departamentos.update', $departamento->id)}}" method="post">
  			@method('PATCH')
  			@csrf

  			<div class="form-group">
  			<label form="nombre">Nombre</label>
  			<input type="text" class="form-control" name="nombre" value="{{$departamento->nombre}}">
  			</div>



  			<button type="submit" class="btn btn-primary">Actualizar</button>
  			<a href="{{ url()->previous() }}" class="btn btn-danger">Cancelar</a>
  		</form>
		</div>
	</div>
@endsection

resources/views/departamentos/index.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Departamentos</title>
@endsection
@section('content')

  @if(session()->get('mensaje'))
    <p id="EditMessage" hidden>
  		{{session()->get('mensaje')}}
  	</p>
  @endif
  <div class="container">
  	<h1>Departamentos</h1>

  	<hr/>

  	@if(session()->get('mensaje'))
  	<div class="alert alert-succes">

  		{{session()->get('mensaje')}}
  	</div><br>

  	@endif
    <div id="toolbar">
      <p id="ActiveRoute" hidden>/departamentos/</p>
      <a href="{{route('departamentos.create')}}" title="Nuevo" class="btn btn-primary"><i class="fa fa-plus-circle"></i> </a>
      <button id="BtnMostrar" title="Mostrar" class="btn btn-secondary"><i class="fa fa-eye"></i></button>
      <button id="BtnEditar" title="Editar" class="btn btn-success"><i class="fa fa-edit"></i></button>
      <button id="BtnEliminar" title="Eliminar" class="btn btn-danger"><i class="fa fa-trash"></i></button>
    </div>
    <table
      id="tableInv"
      data-toggle="table"
      data-locale="es-MX"
      data-show-footer="true"
      data-show-refresh="true"
      data-sort-class="table-active"
      data-sortable="true"
      data-search="true"
      data-toolbar="#toolbar"
      data-single-select="true"
      data-click-to-select="true"
      data-page-list="[10, 25, 50, 100, All]"
      data-url="/listd"
      data-pagination="true">
      <thead>
        <tr>
          <th data-field="state" data-checkbox="true"></th>
          <th data-field="id" data-sortable="true">ID</th>
          <th data-field="nombre" data-sortable="true">Nombre</th>
        </tr>
      </thead>

    </table>

  </div>
@endsection

resources/views/departamentos/show.blade.php
@extends('layouts.app')

@section('titulo')
  <title>{{$departamento->nombre}}</title>
@endsection
@section('content')
  <div class="container">
  	<h1>Inventario del Departamento de {{$departamento->nombre}}</h1>

  	<hr/>

  	@if(session()->get('mensaje'))
  	<div class="alert alert-succes">

  		{{session()->get('mensaje')}}
  	</div><br>

  	@endif
    <h4>Computadoras</h4>
    <div id="toolbarC">
      <a href="{{route('computadoras.create')}}" title="Nuevo" class="btn btn-primary"><i class="fa fa-plus-circle"></i> </a>
      <a href="javascript:;" id="EditarC" title="Editar" class="btn btn-success"><i class="fa fa-edit"></i></a>
      <a href="" id="EliminarC" title="Eliminar" class="btn btn-danger"><i class="fa fa-trash"></i></a>
    </div>
    <table
      id="tableC"
      data-locale="es-MX"
      data-show-footer="true"
      data-show-export="true"
      data-export-types='["json", "xml", "csv", "txt", "pdf"]'
      data-export-options='{"fileName": "ComputadorasDepartamento", "jspdf": {"orientation":"landscape", "margins":{"left":30,"right":30,"bottom":30,"top":30}}}'
      data-show-refresh="true"
      data-toggle="table"
      data-sort-class="table-active"
      data-sortable="true"
      data-search="true"
      data-single-select="true"
      data-click-to-select="true"
      data-toolbar="#toolbarC"
      data-page-list="[10, 25, 50, 100, All]"
      data-url="/listcd"
      data-query-params="queryParams"
      data-pagination="true">
      <thead>
        <tr>
          <th data-field="state" data-checkbox="true"></th>
          <th data-field="id" data-sortable="true">ID</th>
          <th data-field="Nombre" data-sortable="true">Nombre</th>
          <th data-field="SO" data-sortable="true">S.O</th>
          <th data-field="Ram" data-sortable="true">Ram</th>
          <th data-field="Disco" data-sortable="true">Disco</th>
          <th data-field="Procesador" data-sortable="true">Procesador</th>
          <th data-field="Modelo" data-sortable="true">Modelo</th>
          <th data-field="Direccion_Ip" data-sortable="false">IP</th>
          <th data-field="Caracteristicas" data-sortable="false">Caracteristicas</th>
        </tr>
      </thead>

    </table><br><hr/>

    <h4>Impresoras</h4>
    <div id="toolbarI">
      <a href="{{route('impresoras.create')}}" title="Nuevo" class="btn btn-primary"><i class="fa fa-plus-circle"></i> </a>
      <a href="javascript:;" id="EditarI" title="Editar" class="btn btn-success"><i class="fa fa-edit"></i></a>
      <a href="" id="EliminarI" title="Eliminar" class="btn btn-danger"><i class="fa fa-trash"></i></a>
    </div>
    <table
      id="tableI"
      data-locale="es-MX"
      data-show-footer="true"
      data-show-export="true"
      data-export-types='["json", "xml", "csv", "txt", "pdf"]'
      data-export-options='{"fileName": "ImpresorasDepartamento", "jspdf": {"orientation":"landscape", "margins":{"left":30,"right":30,"bottom":30,"top":30}}}'
      data-show-refresh="true"
      data-toggle="table"
      data-sort-class="table-active"
      data-sortable="true"
      data-search="true"
      data-toolbar="#toolbarI"
      data-single-select="true"
      data-click-to-select="true"
      data-page-list="[10, 25, 50, 100, All]"
      data-url="/listid"
      data-query-params="queryParams"
      data-pagination="true">
      <thead>
        <tr>
          <th data-field="state" data-checkbox="true"></th>
          <th data-field="id" data-sortable="true">ID</th>
          <th data-field="Marca" data-sortable="true">Marca</th>
          <th data-field="Caracteristicas" data-sortable="true">Caracteristicas</th>
        </tr>
      </thead>

    </table>
  </div>
@endsection